name: Article Management

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  article-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run article actions
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        ACTION: ${{ github.event.action }}
        ARTICLE_ID: ${{ github.event.inputs.articleId }}
        TITLE: ${{ github.event.inputs.title }}
        CONTENT: ${{ github.event.inputs.content }}
        PATH: ${{ github.event.inputs.path }}
      run: node scripts/article-actions.js
